const cards = [
  ["Happy", "Sad"],
  ["Friendly", "Unfriendly"],
  ["Confident", "Insecure"],
  ["Optimistic", "Pessimistic"],
  ["Generous", "Selfish"],
  ["Brave", "Fearful"],
  ["Polite", "Rude"],
  ["Honest", "Dishonest"],
  ["Calm", "Anxious"],
  ["Loyal", "Disloyal"],
  ["Kind", "Cruel"],
  ["Patient", "Impatient"],
  ["Open-minded", "Close-minded"],
  ["Energetic", "Lethargic"],
  ["Helpful", "Unhelpful"],
  ["Cheerful", "Gloomy"],
  ["Caring", "Indifferent"],
  ["Respectful", "Disrespectful"],
  ["Responsible", "Irresponsible"],
  ["Tolerant", "Intolerant"],
];
